Repository playframework/play-scala-seed.g8, pull requests merged in 2019-01, with the labels that each got.

#79 Upgrade branch 2.7.x using TemplateControl
  project/build.properties
  src/main/g8/build.gradle
  src/main/g8/build.sbt
  src/main/g8/project/plugins.sbt
Labels: merge-when-green, template-control

#78 Upgrade branch 2.6.x using TemplateControl
  .travis.yml
  project/build.properties
  scripts/script-helper
  scripts/test-gradle
  scripts/test-sbt
  src/main/g8/build.gradle
  src/main/g8/build.sbt
  src/main/g8/project/build.properties
Labels: merge-when-green, template-control

#37 Update license
  COPYING
  LICENSE
Labels: backlog

#86 [2.7.x] Upgrade to Play 2.7.0-RC8
  .travis.yml
  src/main/g8/build.gradle
  src/main/g8/project/plugins.sbt
Labels: merge-when-green

#89 Upgrade branch 2.7.x using TemplateControl
  .travis.yml
  build.sbt
  project/build.properties
  project/giter8.sbt
  src/main/g8/build.gradle
  src/main/g8/build.sbt
Labels: merge-when-green, template-control

#91 [2.6.x] Declare plugins in plugins.sbt
  build.sbt
  project/plugins.sbt
  src/main/g8/project/plugins.sbt
  src/main/g8/project/scaffold.sbt
Labels: merge-when-green

#88 Upgrade branch 2.6.x using TemplateControl
  LICENSE
  src/main/g8/build.gradle
  src/main/g8/project/plugins.sbt
Labels: merge-when-green, template-control

#96 Upgrade branch 2.7.x using TemplateControl
  .travis.yml
  LICENSE
  NOTICE
  src/main/g8/build.gradle
  src/main/g8/project/plugins.sbt
Labels: merge-when-green, template-control

#101 Upgrade branch 2.6.x using TemplateControl
  .mergify.yml
  LICENSE
  NOTICE
  src/main/g8/project/plugins.sbt
Labels: merge-when-green, template-control

#102 Upgrade branch 2.6.x using TemplateControl
  .mergify.yml
Labels: merge-when-green
